@startuml

skin BlueModern

title Login flow

participant Client
participant Server

autonumber
Client -> Server: Authentication request
Client <- Server: Authentication response
Client <- Server: StartupInfo [authenticated = true]

@enduml