// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package arch.galaxyeclipse.shared.protocol;

public final class GalaxyEclipseProtocol {
  private GalaxyEclipseProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;
    /**
     * <code>required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;</code>
     */
    arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type getType();
  }
  /**
   * Protobuf type {@code arch.galaxyeclipse.shared.protocol.Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessage
      implements PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Packet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Packet defaultInstance;
    public static Packet getDefaultInstance() {
      return defaultInstance;
    }

    public Packet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type value = arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.internal_static_arch_galaxyeclipse_shared_protocol_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.internal_static_arch_galaxyeclipse_shared_protocol_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.class, arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Builder.class);
    }

    public static com.google.protobuf.Parser<Packet> PARSER =
        new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code arch.galaxyeclipse.shared.protocol.Packet.Type}
     *
     * <pre>
     * Remember that 1-15 are faster
     * </pre>
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AUTH_REQUEST = 16;</code>
       */
      AUTH_REQUEST(0, 16),
      /**
       * <code>AUTH_RESPONSE = 17;</code>
       */
      AUTH_RESPONSE(1, 17),
      ;

      /**
       * <code>AUTH_REQUEST = 16;</code>
       */
      public static final int AUTH_REQUEST_VALUE = 16;
      /**
       * <code>AUTH_RESPONSE = 17;</code>
       */
      public static final int AUTH_RESPONSE_VALUE = 17;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 16: return AUTH_REQUEST;
          case 17: return AUTH_RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:arch.galaxyeclipse.shared.protocol.Packet.Type)
    }

    private int bitField0_;
    // required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type type_;
    /**
     * <code>required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;</code>
     */
    public arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type getType() {
      return type_;
    }

    private void initFields() {
      type_ = arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type.AUTH_REQUEST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code arch.galaxyeclipse.shared.protocol.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.internal_static_arch_galaxyeclipse_shared_protocol_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.internal_static_arch_galaxyeclipse_shared_protocol_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.class, arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Builder.class);
      }

      // Construct using arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type.AUTH_REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.internal_static_arch_galaxyeclipse_shared_protocol_Packet_descriptor;
      }

      public arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet getDefaultInstanceForType() {
        return arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.getDefaultInstance();
      }

      public arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet build() {
        arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet buildPartial() {
        arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet result = new arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet) {
          return mergeFrom((arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet other) {
        if (other == arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;
      private arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type type_ = arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type.AUTH_REQUEST;
      /**
       * <code>required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;</code>
       */
      public arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type getType() {
        return type_;
      }
      /**
       * <code>required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;</code>
       */
      public Builder setType(arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .arch.galaxyeclipse.shared.protocol.Packet.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = arch.galaxyeclipse.shared.protocol.GalaxyEclipseProtocol.Packet.Type.AUTH_REQUEST;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:arch.galaxyeclipse.shared.protocol.Packet)
    }

    static {
      defaultInstance = new Packet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:arch.galaxyeclipse.shared.protocol.Packet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_arch_galaxyeclipse_shared_protocol_Packet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arch_galaxyeclipse_shared_protocol_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\"arch.galaxyeclipse.sha" +
      "red.protocol\"t\n\006Packet\022=\n\004type\030\001 \002(\0162/.a" +
      "rch.galaxyeclipse.shared.protocol.Packet" +
      ".Type\"+\n\004Type\022\020\n\014AUTH_REQUEST\020\020\022\021\n\rAUTH_" +
      "RESPONSE\020\021B\031B\025GalaxyEclipseProtocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_arch_galaxyeclipse_shared_protocol_Packet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_arch_galaxyeclipse_shared_protocol_Packet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_arch_galaxyeclipse_shared_protocol_Packet_descriptor,
              new java.lang.String[] { "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
